from tkinter import *
ghar=Tk()
ghar.title("AutoDice")
ghar.geometry("1000x1000")
papa=Menu(ghar)
baccha=Menu()
baccha.add_command(label='New')
baccha.add_separator()
baccha.add_command(label='Open')
baccha.add_separator()
baccha.add_command(label='Save')
papa.add_cascade(label='File', menu=baccha)

papa.add_command(label='Edit')
papa.add_command(label='Run')
papa.add_command(label='View')
papa.add_command(label='Settings')
papa.add_command(label='Help')
file=Menu(papa)
ghar.config(menu=papa)
ghar.mainloop()
